<a href="https://colab.research.google.com/github/FitriFatimah6/TUBES-PROJECT-UAS/blob/main/Copy_of_Kel1_Fish_Dataset_Pandas(Prosses).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Library

In [1]:
# 1. Import pustaka
import pandas as pd
from google.colab import files
import matplotlib as plt

# Baca Data

In [2]:
# 3. Load semua dataset
df_fish = pd.read_csv("/content/fish_dataset.csv")
df_categories = pd.read_csv("/content/fish_categories_dataset.csv")
df_locations = pd.read_csv("/content/fish_locations_dataset.csv")
df_fishers = pd.read_csv("/content/fishers_dataset.csv")
df_prices = pd.read_csv("/content/fish_market_prices_dataset.csv")

# Data Cleaning

In [3]:
# 1. Cek missing values untuk fish_dataset
missing_values = df_fish.isnull().sum().to_frame().T
missing_values

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,0,1,3,1,0,0,0,1,0,0,0

In [4]:
# 2.1 Mengisi Nilai Kosong (Missing Values) pada Kolom Panjang Ikan
median_length = df_fish['length_cm'].median()
df_fish['length_cm'] = df_fish['length_cm'].fillna(median_length)
df_fish.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [5]:
# 2.2 Mengisi Nilai Kosong pada Kolom fish_name dengan Modus
modus_fish_name = df_fish['fish_name'].mode()[0]
df_fish['fish_name'] = df_fish['fish_name'].fillna(modus_fish_name)
df_fish.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [6]:
# 2.3 Isi missing value di kolom weight_kg (numeric) dengan median
median_weight = df_fish['weight_kg'].median()
df_fish['weight_kg'] = df_fish['weight_kg'].fillna(median_weight)
df_fish.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [7]:
# 2.4 Isi missing value di kolom catch_date (tanggal) dengan modus
modus_date = df_fish['catch_date'].mode()[0]
df_fish['catch_date'] = df_fish['catch_date'].fillna(modus_date)
df_fish.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [8]:
# 2.5 Isi missing value di kolom freshness_score (bisa numeric atau kategori)
# Kalau numerik → median; kalau kategori → modus. kita pakai modus:
modus_freshness = df_fish['freshness_score'].mode()[0]
df_fish['freshness_score'] = df_fish['freshness_score'].fillna(modus_freshness)
df_fish.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [9]:
# 3. Hapus data duplikat berdasarkan fish_id
fish_df = df_fish.drop_duplicates(subset='fish_id')
fish_df.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244

In [10]:
# Cek kembali apakah masih ada missing values
df_fish.isnull().sum()

fish_id            0
fish_name          0
weight_kg          0
length_cm          0
catch_date         0
province           0
fishing_method     0
freshness_score    0
category_id        0
location_id        0
fisher_id          0
dtype: int64

# Cleaning Categori

In [11]:
# 1. Cek missing values untuk categories
missing_values = df_categories.isnull().sum().to_frame().T
missing_values

   category_id  category_name  habitat  avg_price_per_kg
0            0              0        0                 0

# Cleaning Location

In [12]:
# Cek missing values
missing_market = df_locations.isnull().sum().to_frame().T
missing_market

,location_id,location_name,latitude,longitude,water_depth_m,temperature_celsius,salinity_ppt
0,0,0,0,0,0,0,0

# Cleaning Fisher

In [13]:
# Cek missing values
missing_market = df_fishers.isnull().sum().to_frame().T
missing_market

,fisher_id,fisher_name,experience_years,boat_type,boat_capacity_kg,home_port,license_number
0,0,0,0,0,0,0,0

In [14]:
# Cek kembali apakah masih ada missing values
df_fish.isnull().sum()

fish_id            0
fish_name          0
weight_kg          0
length_cm          0
catch_date         0
province           0
fishing_method     0
freshness_score    0
category_id        0
location_id        0
fisher_id          0
dtype: int64

# Join Operation

In [15]:
# Langkah 1: Lakukan inner join antara fish dan fish_categories berdasarkan category_id
joined_df = pd.merge(df_fish, df_categories, on='category_id', how='inner')
joined_df.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id,category_name,habitat,avg_price_per_kg
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381,Freshwater Fish,Rivers/Lakes,45000
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337,Freshwater Fish,Rivers/Lakes,45000
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144,Demersal Fish,Sea Bottom,120000
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271,Pelagic Fish,Open Ocean,85000
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244,Reef Fish,Coral Reef,150000

In [16]:
# Langkah 2: Inner join dengan fish_locations berdasarkan location_id
joined_df = pd.merge(joined_df, df_locations, on='location_id', how='inner')
joined_df.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,fisher_id,category_name,habitat,avg_price_per_kg,location_name,latitude,longitude,water_depth_m,temperature_celsius,salinity_ppt
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,381,Freshwater Fish,Rivers/Lakes,45000,Laut Jawa Zone D,-8.014815,100.237065,2780,29.8,33.5
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,337,Freshwater Fish,Rivers/Lakes,45000,Laut Flores Zone B,-3.052861,139.649345,728,24.0,33.4
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,144,Demersal Fish,Sea Bottom,120000,Laut Jawa Zone H,0.689541,101.236256,2306,24.8,33.7
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,271,Pelagic Fish,Open Ocean,85000,Laut Banda Zone C,-6.811777,137.613943,2682,27.2,32.1
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,244,Reef Fish,Coral Reef,150000,Laut Natuna Zone J,4.826068,110.349063,59,28.7,31.0

In [17]:
# Langkah 3: Inner join dengan fishers berdasarkan fisher_id
joined_df = pd.merge(joined_df, df_fishers, on='fisher_id', how='inner')
joined_df.head()

,fish_id,fish_name,weight_kg,length_cm,catch_date,province,fishing_method,freshness_score,category_id,location_id,...,longitude,water_depth_m,temperature_celsius,salinity_ppt,fisher_name,experience_years,boat_type,boat_capacity_kg,home_port,license_number
0,1,Catfish,19.83,115.1,7/6/2023,Papua,Trap,3.0,4,4,...,100.237065,2780,29.8,33.5,Nelayan_381,26,Motor Boat,3264,Sulawesi Selatan,LIC250393
1,2,Carp,21.02,101.8,11/19/2023,Sulawesi Selatan,Hand Line,10.0,4,12,...,139.649345,728,24.0,33.4,Nelayan_337,19,Motor Boat,4236,Sulawesi Selatan,LIC493492
2,3,Anchovy,43.10,184.4,5/1/2023,Jawa Timur,Purse Seine,4.0,2,18,...,101.236256,2306,24.8,33.7,Nelayan_144,10,Motor Boat,3465,Sumatera Utara,LIC411388
3,4,Sole,36.27,106.9,5/25/2023,Maluku,Gill Net,10.0,1,13,...,137.613943,2682,27.2,32.1,Nelayan_271,5,Motor Boat,1004,Bali,LIC129483
4,5,Sole,15.70,162.8,3/29/2023,Jawa Timur,Trawling,2.0,3,20,...,110.349063,59,28.7,31.0,Nelayan_244,13,Trawler,379,Papua,LIC188541